import Navbar from "./layout/Navbar";
import Footer from "./layout/Footer";
import localFont from "next/font/local";

/*import ScrollToContent from "./components/ScrollToContent";*/

import "./globals.css";

const introRust = localFont({
  src: ".//fonts/IntroRust-Base.otf",
});

const instrumentSans = localFont({
  src: ".//fonts/InstrumentSans.ttf",
  weight: "600",
  subsets: ["latin"],
});

export const metadata = {
  title: "Good Boys Dog Grooming",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${introRust.variable} ${instrumentSans.variable}`}>
        {/*<ScrollToContent />*/}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
