import Navbar from "./layout/Navbar";
import Footer from "./layout/Footer";
import localFont from "next/font/local";
import "./globals.css";

const introRust = localFont({
  src: ".//fonts/IntroRust-Base.otf",
});

export const metadata = {
  title: "Good Boys Dog Grooming",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${introRust.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
